app:
    resource: "@AppBundle/Controller/"
    type:     annotation

glukose_enjolras:
    resource: "@GlukoseEnjolrasBundle/Resources/config/routing.yml"
    prefix:   /

glukose_user:
    resource: "@GlukoseUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

#SONATA ADMIN Bundle routes
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"
