# app/config/security.yml
security:
  # Preserve plain text password in token for refresh the user.
  # Analyze the security considerations before turn off this setting.
  erase_credentials: false

  firewalls:
    main:
      pattern:    ^/
      fr3d_ldap:  ~
      form_login:
          always_use_default_target_path: true
          default_target_path: /sujets
          #target_path_parameter: _target_path
          success_handler: glukose_user.component.authentication.handler.login_success_handler
      logout:     true
      anonymous:  true

  providers:
    chain_provider:
      chain:
        #providers: [fos_userbundle]
        providers: [fos_userbundle, fr3d_ldapbundle]
    fr3d_ldapbundle:
      id: fr3d_ldap.security.user.provider

    fos_userbundle:
      id: fos_user.user_provider.username

  encoders:
    AcmeBundle\Acme\User\LdapUser: plaintext
    Glukose\UserBundle\Entity\User: sha512

  access_control:
    - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }

  role_hierarchy:
    ROLE_ADMIN:       ROLE_USER
    ROLE_SUPER_ADMIN: ROLE_ADMIN
