# Route de connexion au Backoffice
fos_admin_user_security_login:
    path:  /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }
 
# Route de vérification de connexion au Backoffice
fos_admin_user_security_checkA:
    path:  /admin/check
    defaults: { _controller: FOSUserBundle:Security:check }
    requirements:
        _method: POST
 
# Route de déconnexion du Backoffice
fos_admin_user_security_logout:
    path:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }