glukose_enjolras_homepage:
    path:     /
    defaults: { _controller: GlukoseEnjolrasBundle:Main:index }

glukose_enjolras_subjects:
    path:     /sujets
    defaults: { _controller: GlukoseEnjolrasBundle:Main:showAllSubjects }
    
glukose_enjolras_oneSubject:
    path:     /sujet/{idSubject}
    defaults: { _controller: GlukoseEnjolrasBundle:Main:showSubject, idSubject:'1' }

glukose_enjolras_voteCondorcet:
    path:     /sujet/vote/condorcet/{idSubject}
    defaults: { _controller: GlukoseEnjolrasBundle:Main:voteCondorcet, idSubject:'1' }
    
glukose_enjolras_cloture_vote:
    path:     /sujet/vote/cloture/condorcet/{idSubject}
    defaults: { _controller: GlukoseEnjolrasBundle:Main:clotureCondorcet, idSubject:'1' }
    
glukose_enjolras_publication_resultats:
    path:     /sujet/vote/resultats/{idSubject}
    defaults: { _controller: GlukoseEnjolrasBundle:Main:publicationResultat, idSubject:'1' }
